events {}

http {
    upstream ticket_servers {
        server 10.0.1.212:5000; # IP privada de api 1, al deplegar en AWS podia cambiar, revisar en la consola de AWS
        
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ticket_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}